# Generated by Django 5.1.14 on 2025-11-06 07:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('document_id', models.CharField(blank=True, help_text='CPF/CNPJ ou outro identificador', max_length=20, verbose_name='Documento')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número da OS')),
                ('title', models.CharField(default='Ordem de Serviço', max_length=120, verbose_name='Título')),
                ('issue_description', models.TextField(verbose_name='Descrição do problema')),
                ('status', models.CharField(choices=[('received', 'Recebida'), ('diagnosis', 'Em diagnóstico'), ('waiting_approval', 'Aguardando aprovação'), ('approved', 'Aprovada'), ('in_progress', 'Em execução'), ('ready', 'Pronta para entrega'), ('delivered', 'Finalizada'), ('canceled', 'Cancelada')], default='received', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Previsão de entrega')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de entrega')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Notas para o cliente')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer', verbose_name='Cliente')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('labor', 'Mão de obra'), ('part', 'Peça'), ('service', 'Serviço terceirizado'), ('other', 'Outros')], default='labor', max_length=20, verbose_name='Categoria')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=7, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor unitário')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.serviceorder', verbose_name='Ordem de serviço')),
            ],
            options={
                'verbose_name': 'Item da OS',
                'verbose_name_plural': 'Itens da OS',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('pix', 'PIX'), ('bank_transfer', 'Transferência'), ('other', 'Outro')], default='cash', max_length=20, verbose_name='Forma de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.serviceorder', verbose_name='Ordem de serviço')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('received', 'Recebida'), ('diagnosis', 'Em diagnóstico'), ('waiting_approval', 'Aguardando aprovação'), ('approved', 'Aprovada'), ('in_progress', 'Em execução'), ('ready', 'Pronta para entrega'), ('delivered', 'Finalizada'), ('canceled', 'Cancelada')], max_length=20, verbose_name='Status anterior')),
                ('to_status', models.CharField(choices=[('received', 'Recebida'), ('diagnosis', 'Em diagnóstico'), ('waiting_approval', 'Aguardando aprovação'), ('approved', 'Aprovada'), ('in_progress', 'Em execução'), ('ready', 'Pronta para entrega'), ('delivered', 'Finalizada'), ('canceled', 'Cancelada')], max_length=20, verbose_name='Status atual')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.serviceorder', verbose_name='Ordem de serviço')),
            ],
            options={
                'verbose_name': 'Histórico de status',
                'verbose_name_plural': 'Histórico de status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(blank=True, max_length=10, verbose_name='Placa')),
                ('brand', models.CharField(max_length=80, verbose_name='Marca')),
                ('model', models.CharField(max_length=80, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Cor')),
                ('vin', models.CharField(blank=True, max_length=32, verbose_name='Chassi')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['plate', 'brand', 'model'],
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.vehicle', verbose_name='Veículo'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('plate', ''), _negated=True), fields=('customer', 'plate'), name='unique_vehicle_plate_per_customer'),
        ),
    ]
