# Generated by Django 5.2.6 on 2025-09-26 07:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$', 'Formato: (11) 99999-9999')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'Formato: 000.000.000-00')], verbose_name='CPF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_os', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número OS')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do problema')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('solucao', models.TextField(blank=True, verbose_name='Solução aplicada')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('ORCAMENTO', 'Orçamento'), ('APROVADA', 'Aprovada'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('CONCLUIDA', 'Concluída'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20, verbose_name='Prioridade')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de abertura')),
                ('data_orcamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do orçamento')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovação')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de entrega')),
                ('prazo_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de entrega')),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor mão de obra')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor peças')),
                ('valor_terceiros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor terceiros')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Total')),
                ('km_entrada', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na entrada')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações internas')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável técnico')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor total')),
                ('tipo', models.CharField(choices=[('SERVICO', 'Serviço'), ('PECA', 'Peça'), ('TERCEIRO', 'Terceiro')], default='SERVICO', max_length=20, verbose_name='Tipo')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Serviço',
                'verbose_name_plural': 'Itens da Ordem de Serviço',
            },
        ),
        migrations.CreateModel(
            name='StatusHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('ABERTA', 'Aberta'), ('ORCAMENTO', 'Orçamento'), ('APROVADA', 'Aprovada'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('CONCLUIDA', 'Concluída'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], max_length=20, verbose_name='Status anterior')),
                ('status_novo', models.CharField(choices=[('ABERTA', 'Aberta'), ('ORCAMENTO', 'Orçamento'), ('APROVADA', 'Aprovada'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('CONCLUIDA', 'Concluída'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], max_length=20, verbose_name='Status novo')),
                ('data_mudanca', models.DateTimeField(auto_now_add=True, verbose_name='Data da mudança')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='core.ordemservico', verbose_name='Ordem de Serviço')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-data_mudanca'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}-?\\d{4}$|^[A-Z]{3}\\d[A-Z]\\d{2}$', 'Formato inválido de placa')], verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ano')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('chassi', models.CharField(max_length=50, unique=True, verbose_name='Chassi')),
                ('tipo_veiculo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMINHAO', 'Caminhão'), ('VAN', 'Van'), ('OUTROS', 'Outros')], default='CARRO', max_length=20, verbose_name='Tipo de Veículo')),
                ('batido', models.BooleanField(default=False, verbose_name='Veículo batido?')),
                ('km_atual', models.PositiveIntegerField(verbose_name='Quilometragem Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='core.veiculo', verbose_name='Veículo'),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_agendamento', models.DateTimeField(verbose_name='Data do agendamento')),
                ('servico_solicitado', models.TextField(verbose_name='Serviço solicitado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('compareceu', models.BooleanField(default=False, verbose_name='Compareceu')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('ordem_servico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ordemservico', verbose_name='Ordem de Serviço')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_agendamento'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='core_client_nome_bfa2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf'], name='core_client_cpf_658941_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ativo'], name='core_client_ativo_7d0832_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['placa'], name='core_veicul_placa_8831b8_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['chassi'], name='core_veicul_chassi_a874e6_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['cliente', 'ativo'], name='core_veicul_cliente_94c843_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['numero_os'], name='core_ordems_numero__162ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['status'], name='core_ordems_status_fcd72e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['data_abertura'], name='core_ordems_data_ab_323026_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['veiculo', 'status'], name='core_ordems_veiculo_282c5f_idx'),
        ),
    ]
