# Generated by Django 5.2.6 on 2025-10-09 03:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordemservico',
            name='dar_baixa_estoque',
            field=models.BooleanField(default=True, help_text='Desmarque para não movimentar estoque', verbose_name='Dar baixa no estoque'),
        ),
        migrations.AlterField(
            model_name='itemordemservico',
            name='descricao',
            field=models.CharField(help_text='Preencha se for serviço ou item avulso', max_length=255, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='CategoriaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Categoria de Peça',
                'verbose_name_plural': 'Categorias de Peças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'Formato: 00.000.000/0000-00')], verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$', 'Formato: (11) 99999-9999')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'Formato: 00000-000')], verbose_name='CEP')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Nome do Contato')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantidade_estoque', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Estoque Mínimo')),
                ('estoque_maximo', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Estoque Máximo')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('PAR', 'Par'), ('CJ', 'Conjunto'), ('M', 'Metro'), ('L', 'Litro'), ('KG', 'Quilograma'), ('CX', 'Caixa')], default='UN', max_length=10, verbose_name='Unidade de Medida')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Venda')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira A1, Setor 3', max_length=100, verbose_name='Localização no Estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_fabricante', models.CharField(blank=True, max_length=100, verbose_name='Código do Fabricante')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='Código de Barras')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='core.categoriapeca', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='core.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('DEVOLUCAO', 'Devolução'), ('PERDA', 'Perda'), ('TRANSFERENCIA', 'Transferência')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Anterior')),
                ('quantidade_nova', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Nova')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor Total')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('numero_documento', models.CharField(blank=True, help_text='NF, Pedido, etc.', max_length=50, verbose_name='Número do Documento')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='core.ordemservico', verbose_name='Ordem de Serviço')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.peca', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddField(
            model_name='itemordemservico',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_ordem', to='core.peca', verbose_name='Peça'),
        ),
        migrations.AddIndex(
            model_name='categoriapeca',
            index=models.Index(fields=['nome'], name='core_catego_nome_92c789_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['nome'], name='core_fornec_nome_3185fc_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['cnpj'], name='core_fornec_cnpj_fb8a37_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['codigo'], name='core_peca_codigo_480eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['nome'], name='core_peca_nome_bc8467_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['categoria', 'ativo'], name='core_peca_categor_1b4990_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['codigo_barras'], name='core_peca_codigo__9bd824_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['peca', '-data_movimentacao'], name='core_movime_peca_id_180695_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', '-data_movimentacao'], name='core_movime_tipo_758fb2_idx'),
        ),
    ]
