# Generated by Django 5.1.14 on 2025-11-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='diagnosis_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Diagnóstico concluído em'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='diagnosis_description',
            field=models.TextField(blank=True, verbose_name='Diagnóstico técnico'),
        ),
    ]
