# Generated by Django 5.1.14 on 2025-11-06 07:38

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serviceorder_diagnosis_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('vehicle_photo', 'Foto do veículo'), ('receipt', 'Comprovante / cupom fiscal')], default='vehicle_photo', max_length=20, verbose_name='Categoria')),
                ('file', models.FileField(upload_to=core.models.attachment_upload_to, verbose_name='Arquivo')),
                ('description', models.CharField(blank=True, help_text='Ex.: detalhe do dano, número do cupom.', max_length=120, verbose_name='Descrição')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.serviceorder', verbose_name='Ordem de serviço')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo da OS',
                'verbose_name_plural': 'Anexos da OS',
                'ordering': ['-created_at'],
            },
        ),
    ]
