# Generated by Django 5.2.6 on 2025-10-29 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemordemservico_dar_baixa_estoque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('imagem', models.ImageField(upload_to='ordens/%Y/%m/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=120, verbose_name='Legenda')),
            ],
            options={
                'verbose_name': 'Foto da Ordem de Serviço',
                'verbose_name_plural': 'Fotos das Ordens de Serviço',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='estimate_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Serviço padrão (preço conhecido)'), ('PERSONALIZADO', 'Sob diagnóstico')], max_length=20, verbose_name='Tipo de orçamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='orcamento_aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovação'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='orcamento_requer_reaprovacao',
            field=models.BooleanField(default=False, verbose_name='Requer reaprovação?'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='orcamento_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='orcamento_total_aprovado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total aprovado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='orcamento_total_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total estimado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='requires_diagnosis',
            field=models.BooleanField(default=False, verbose_name='Requer diagnóstico'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('DIAGNOSTICO', 'Em diagnóstico'), ('ORCAMENTO', 'Orçamento interno'), ('ORCAMENTO_ENVIADO', 'Orçamento enviado'), ('APROVADA', 'Aprovada'), ('EM_ANDAMENTO', 'Em execução'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('CONCLUIDA', 'Concluída'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='statushistorico',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('ABERTA', 'Aberta'), ('DIAGNOSTICO', 'Em diagnóstico'), ('ORCAMENTO', 'Orçamento interno'), ('ORCAMENTO_ENVIADO', 'Orçamento enviado'), ('APROVADA', 'Aprovada'), ('EM_ANDAMENTO', 'Em execução'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('CONCLUIDA', 'Concluída'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], max_length=20, verbose_name='Status anterior'),
        ),
        migrations.AlterField(
            model_name='statushistorico',
            name='status_novo',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('DIAGNOSTICO', 'Em diagnóstico'), ('ORCAMENTO', 'Orçamento interno'), ('ORCAMENTO_ENVIADO', 'Orçamento enviado'), ('APROVADA', 'Aprovada'), ('EM_ANDAMENTO', 'Em execução'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('CONCLUIDA', 'Concluída'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], max_length=20, verbose_name='Status novo'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['orcamento_token'], name='core_ordems_orcamen_0409cd_idx'),
        ),
        migrations.AddField(
            model_name='fotoordemservico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='fotoordemservico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='fotoordemservico',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.ordemservico', verbose_name='Ordem de Serviço'),
        ),
    ]
