# Generated by Django 5.2.6 on 2025-10-29 04:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fotoordemservico_ordemservico_estimate_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo inicial')),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido')),
                ('troco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco')),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_DEBITO', 'Cartão de débito'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('BOLETO', 'Boleto'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Forma de pagamento')),
                ('parcelas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Parcelas')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ESTORNADO', 'Estornado')], default='PAGO', max_length=15, verbose_name='Status')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.ordemservico', verbose_name='Ordem de Serviço')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_DEBITO', 'Cartão de débito'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('BOLETO', 'Boleto'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Forma de pagamento')),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do lançamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.caixa', verbose_name='Caixa')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.pagamentoordemservico', verbose_name='Pagamento relacionado')),
            ],
            options={
                'verbose_name': 'Lançamento de Caixa',
                'verbose_name_plural': 'Lançamentos de Caixa',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.AddIndex(
            model_name='pagamentoordemservico',
            index=models.Index(fields=['status'], name='core_pagame_status_2553c9_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoordemservico',
            index=models.Index(fields=['forma_pagamento'], name='core_pagame_forma_p_758f03_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoordemservico',
            index=models.Index(fields=['data_pagamento'], name='core_pagame_data_pa_422cab_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocaixa',
            index=models.Index(fields=['tipo'], name='core_lancam_tipo_5db771_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocaixa',
            index=models.Index(fields=['forma_pagamento'], name='core_lancam_forma_p_55fba4_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocaixa',
            index=models.Index(fields=['data_lancamento'], name='core_lancam_data_la_29af3c_idx'),
        ),
    ]
