# Generated by Django 5.1.14 on 2025-11-06 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serviceattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='approval_channel',
            field=models.CharField(blank=True, choices=[('in_person', 'Presencial'), ('phone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('other', 'Outro')], max_length=20, verbose_name='Canal de aprovação'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='approval_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovação registrada em'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='approval_confirmed_by',
            field=models.CharField(blank=True, help_text='Nome do cliente responsável pela aprovação.', max_length=120, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Notas da aprovação'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='approval_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='Aprovação registrada por'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='approval_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor aprovado'),
        ),
    ]
