# Generated by Django 5.1.14 on 2025-11-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviceorder_approval_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='public_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token público'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='public_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token gerado em'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='approval_channel',
            field=models.CharField(blank=True, choices=[('in_person', 'Presencial'), ('phone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('other', 'Outro'), ('public_link', 'Link público')], max_length=20, verbose_name='Canal de aprovação'),
        ),
    ]
