# Generated by Django 5.2.6 on 2025-10-29 05:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_caixa_pagamentoordemservico_lancamentocaixa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPecaOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição da peça')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_COMPRA', 'Em compra'), ('AGUARDANDO_ENTREGA', 'Aguardando entrega'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20, verbose_name='Status')),
                ('previsao_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de entrega')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de recebimento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor', verbose_name='Fornecedor')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_pecas', to='core.ordemservico', verbose_name='Ordem de Serviço')),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.peca', verbose_name='Peça do estoque')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_pecas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_pecas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Requisição de Peça',
                'verbose_name_plural': 'Requisições de Peças',
                'ordering': ['status', 'criado_em'],
                'indexes': [models.Index(fields=['status'], name='core_pedido_status_f6eb0e_idx'), models.Index(fields=['previsao_entrega'], name='core_pedido_previsa_df61fe_idx')],
            },
        ),
    ]
