# Generated by Django 5.1.14 on 2025-11-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_serviceorder_public_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='public_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token expira em'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='public_token_revoked',
            field=models.BooleanField(default=False, verbose_name='Token revogado'),
        ),
    ]
