# Generated by Django 5.1.14 on 2025-11-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serviceorder_public_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='execution_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Execução finalizada em'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='execution_notes',
            field=models.TextField(blank=True, verbose_name='Notas da execução'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='execution_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Execução iniciada em'),
        ),
    ]
